# Generated by Django 5.0.7 on 2024-10-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_developer',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
