# Generated by Django 5.0.7 on 2024-10-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anaylzer', '0002_mockinterview'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockinterview',
            name='answers',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='rating',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='review',
            field=models.TextField(default=''),
        ),
    ]
