# Generated by Django 5.0.7 on 2024-09-15 10:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CompanyProfile', '0001_initial'),
        ('Utility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('posted_date', models.DateField(default=django.utils.timezone.now)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Utility.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyProfile.company')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Utility.location')),
            ],
            options={
                'verbose_name': 'Job Listing',
                'verbose_name_plural': 'Job Listings',
                'db_table': 'jobsearch__joblisting',
                'ordering': ['posted_date'],
            },
        ),
    ]
